name: sistema_vistorias
description: Sistema de Vistorias Técnicas
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  supabase_flutter: ^1.10.25
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.2
  flutter_local_notifications: ^16.2.0
  image_picker: ^1.0.4
  uuid: ^4.2.1
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  timezone: ^0.9.2
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

flutter:
  uses-material-design: true
  assets:
    - .env.development
    - .env.staging
    - .env.production
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
